# Generated by Django 4.2.11 on 2024-03-24 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.CharField(max_length=200)),
                ('winner', models.IntegerField(choices=[(0, 'Yourself'), (1, 'Opponent')], default=0)),
                ('first_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_played', to=settings.AUTH_USER_MODEL)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_list', to='games.gamelisting')),
            ],
        ),
    ]
