# Generated by Django 4.2.11 on 2024-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
